apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-connect
spec:
  capacity:
    storage: ${CONNECT_SHARED_STORAGE}Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-pv-connect
  mountOptions:
    - tls
    - iam
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${EFS_ID}::${efs_ap_connect}
