## This example requires the Traefik Ingress Controller to be installed ##
#
# For this example, we assume the following resources already exist. They are not created by the chart:
# - A valid TLS secret named `connect-tls` for the host `connect.rstudio.com`
# - A postgres database: `postgres://connect@postgres.rstudio.com:5432/rsc_k8s`
# - An NFS share: `nfs.rstudio.com:/rstudio-connect`

# Controls how many instances of RStudio Connect will be created.
replicas: 1

sharedStorage:
  create: true
  mount: true
  path: /var/lib/rstudio-connect
  storageClassName: efs-pv-connect
  volumeName: efs-pv-connect
  requests:
    storage: 100G


service:
  type: ClusterIP

readinessProbe:
  enabled: false


config:
  HTTP:
    NoWarning: true
  Server:
    # Server.Address matches the FQDN in our TLS certificate.
    Address: "http://${DOMAIN}/pct"

    # Note: `DataDir` has the same value as `pod.volumeMounts.mountPath`.
    DataDir: "/var/lib/rstudio-connect"

  Database:
    Provider: "Postgres"

  Postgres:
    URL: "${POSTGRES_CONNECTION_URI}&options=-csearch_path=posit_connect"
